### ISSUE TITLE
Mixed Monte-Carlo paper link leads to "A Distributional Perspective on Reinforcement Learning"

### ISSUE THREAD

**Issue by nikoliazekter** [NervanaSystems/coach#1]
Supported Algorithms paragraph incorrectly links "A Distributional Perspective on Reinforcement Learning" instead of MMC paper.

**Comment by itaicaspi-intel** [comment]
Thanks. The link was fixed.
Here is the direct link to the paper that makes use of MMC: https://arxiv.org/abs/1703.01310
