### ISSUE TITLE
Dashboard dependency on wx

### ISSUE THREAD

**Issue by bbalaji-ucsd** [NervanaSystems/coach#100]
Cannot get wxPython to install in any of my machines (Mac, Ubuntu). Is there another way to get the dashboard working?

**Comment by itaicaspi-intel** [comment]
wxPython is only used for the open file dialog.
You can bypass it by passing the experiment directory through the command line flag `-d`, or the experiment csv file through the command line flag `-f`.

**Comment by zach-nervana** [comment]
I am running into this problem as well, and providing an experiment directory through the command line doesn't remove the dependency on wx. I am looking into removing this dependency if the open file dialog is not used.

**Comment by scttl** [comment]
If you can do a `pip install rl-coach-slim` instead, this variant of coach doesn't depend on wxPython (or Tensorflow or kubernetes python libraries)

**Comment by zach-nervana** [comment]
the problem is not that coach relies on wx, but the dashboard.

**Comment by zach-nervana** [comment]
my problem is that even though wx is installed, it is expecting a "framework version of python" which i'm not having much luck getting past. A slight refactor to avoid importing packages that aren't actually used is working for now.

**Comment by galnov** [comment]
wxPython dependency removed with PR #207
