### ISSUE TITLE
print_parameters doesn't work

### ISSUE THREAD

**Issue by bbalaji-ucsd** [NervanaSystems/coach#109]
python coach.py -p CartPole_PG --print_parameters

operates in the same way as:
python coach.py -p CartPole_PG

It used to work in earlier versions. It looks like the argument is ignored now.

**Comment by itaicaspi-intel** [comment]
Your right, the `--print_parameters` is a leftover that should have been removed.
In the current version, all the parameters are written by default to a json file in the experiment directory.

**Comment by bbalaji-ucsd** [comment]
Great, thanks!
