### ISSUE TITLE
PPO reference

### ISSUE THREAD

**Issue by joschu** [NervanaSystems/coach#11]
This library looks great -- beautiful work.
The proper reference for PPO is the arxiv paper from my coauthors and me (https://arxiv.org/abs/1707.06347). As acknowledged by Heess et al. in their DPPO paper, their algorithm was based on my github code, which didn't have a corresponding publication at the time.

**Comment by galleibo-intel** [comment]
Hi John,

Glad you liked the framework. 
Thanks a lot, we are great fans of your work!

Sorry for the confusion. 

It is fixed now in the GitHub repo eb0b57d7fad541e59c9a0fce09ec1a9a6e11ec4b, and should also be fixed at http://coach.nervanasys.com and in the [blog post](https://www.intelnervana.com/reinforcement-learning-coach-intel/) in a day or two.

**Comment by joschu** [comment]
Great, thanks!
