### ISSUE TITLE
ClippedPPO does not log loss, value/policy loss, kl divergence

### ISSUE THREAD

**Issue by bbalaji-ucsd** [NervanaSystems/coach#113]
ClippedPPO does not log a number of relevant parameters in the CSV file inside the experiments directory. These include loss, value loss, kl divergence, policy loss. It becomes difficult to debug the training runs without these parameters.

The corresponding columns are empty in the file and the visualization does not show these parameters for graphing.

**Comment by galleibo-intel** [comment]
Hi @bbalaji-ucsd , 
This was indeed a bug. Fixed with 72ea9333846e39e508eaff73b1d96d144d020532. 

Thanks for catching this.
