### ISSUE TITLE
Two typos in coach.py

### ISSUE THREAD

**Issue by yaogang2018** [NervanaSystems/coach#114]
In line 263, 269, 276 of coach.py of master branch, what does the `--experiment_type` means?  And the `--environemnt_type` should be `--environment_type`, just a typo.

One another problem: the file says 

> "If no preset is defined, a preset can be set from the command-line by combining settings "
                             "which are set by using --agent_type, --experiment_type, --environemnt_type"

but it autually shows this thing when I run `coach -at ddpg_agent -et control_suite_environment -ept e-greedy` : 

> Please choose a preset using the -p flag or use the --play flag together with choosing an environment type (-et) in order to play the game.

The arguments help information is outdated?

**Comment by galleibo-intel** [comment]
Hi,
The documentation is indeed outdated. Defining a preset directly from command-line is not supported at the moment. 

The only supported usage for setting an environment_type from command-line is for playing an environment as a HumanAgent, and then using the created dataset for running Behavioral Cloning (imitation learning). 

For example, for playing MontezumaRevenge and creating a dataset, you could use:
```coach  --play -et rl_coach.environments.gym_environment:Atari -lvl MontezumaRevengeDeterministic-v4```

The documentation is indeed a bit lacking on this front and needs to be improved. Thanks for filing the issue.

**Comment by shadiendrawis** [comment]
Fixed with PR #283.
