### ISSUE TITLE
Distributed checkpoints not being saved

### ISSUE THREAD

**Issue by sohakes** [NervanaSystems/coach#118]
Hi,

I was trying to restore the distributed checkpoints, and if I'm not doing anything wrong, they are not being saved (just the summary for tensorboard) even if I pass the `save_checkpoint_secs` parameter. Looking at the coach.py file, it looks like the `save_checkpoint_secs` parameter is not being passed when building `DistributedTaskParameters` (only for the non-distributed on), and so tensorflow doesn't save the checkpoints (since it will be None when starting the `MonitoredTrainingSession`). I added `save_checkpoint_secs=args.save_checkpoint_secs`, and now it seems to save and restore with the cartpole example.

My coach version is slightly outdated from the github now, but from what I saw the parameter is still not being passed.

**Comment by galleibo-intel** [comment]
Fixed with release 0.11.0. If there's still an issue, please re-open the issue.
