### ISSUE TITLE
Scalability for different distribution strategies?

### ISSUE THREAD

**Issue by slerman12** [NervanaSystems/coach#122]
This is an amazing project. My only question is, would this scale to more complex distribution strategies like IMPALA?

**Comment by galleibo-intel** [comment]
Hi Sam,

As of release 0.11.0, Coach supports multi-node distributed training. Currently the implementation is limited to distributing actors, but the plan is to extend to distributing trainers as well. We will then probably add support for IMPALA, or one of the other more recent variants. 

Contributions from the community are of course very welcomed.

**Comment by slerman12** [comment]
Thanks, this is great!
