### ISSUE TITLE
Tutorial import out of date

### ISSUE THREAD

**Issue by hcch0912** [NervanaSystems/coach#123]
In tutorial 2: Adding an Environment.ipybn 
In section The Prese, cell "Now let's define the environment parameters"
 from rl_coach.environments.environment import MaxDumpMethod, SelectedPhaseOnlyDumpMethod, SingleLevelSelection
The import is the out of date, MaxDumpMethod, SelectedPhaseOnlyDumpMethod is no longer in environment.py

**Comment by galleibo-intel** [comment]
Thanks. Fixed with release 0.11.0.
