### ISSUE TITLE
Continue training (CARLA)

### ISSUE THREAD

**Issue by AhmedARadwan** [NervanaSystems/coach#124]
Hello,

First, really great work done in this framework

I'm working on CARLA simulator and I'm encountering an issue. The training happens to fail very often due to a TCP connection error and when it fails I want to continue training from the last checkpoint but I can't find a command to do so. I can evaluate from the last checkpoint but the training doesn't continue.

Does anyone have a solution to this problem?

Thanks,

**Comment by 18605973470** [comment]
You can use '-crd' option to continue training,  I think .

**Comment by AhmedARadwan** [comment]
> You can use '-crd' option to continue training, I think .

I used it with and without --evaluate and it didn't continue the training

**Comment by galnov** [comment]
@AhmedARadwan, can you please share the exact command line you are trying to run? I tried it with the CARLA_DDPG preset and it is working fine.

**Comment by galnov** [comment]
Closing this due to no response. 
If this is still an issue, please reopen.
