### ISSUE TITLE
Documentation Suggestions

### ISSUE THREAD

**Issue by Migdalin** [NervanaSystems/coach#143]
For people, like me, trying to get started with coach:

- Add the installation instructions (or a link explaining where to find them) to the online documents:  https://nervanasystems.github.io/coach/index.html

- Add "sudo" as a prerequisite.  When I try to follow the installation instructions in the readme.md, I immediately get an error saying "sudo is not recognized as an internal or external command, operable program or batch file."  What is sudo?  Where do I get it?  I can figure this out via Google, but it's still an obstacle early on.

**Comment by Migdalin** [comment]
Now that I've gone to Google:  please make clear that coach only runs on an obscure operating system that most people have never heard of, because you've decided that Microsoft and Apple must die.  Seriously, you guys are with Intel?

**Comment by galnov** [comment]
Thanks for the feedback.
As the first line of the installation section in the README states, Coach has only been tested on Ubuntu 16.04 LTS and with Python 3.5. A few users have also got it working on OS X with varying levels of success. 
We'd appreciate any contributions that enable support of additional operating systems.
