### ISSUE TITLE
Action Exploration and Monte Carlo Tree Search?

### ISSUE THREAD

**Issue by aGiant** [NervanaSystems/coach#15]
Hi,
first of all, very great job!!
Only some wishes about your RL library:
1. Action Exploration Settings
2. Monte Carlo Tree Search
So far as I knew, there is no RL library exists togerther with MCTS which is the key method of AlphaGo. If Intel builds standard constructure for MCTS and RL, that would be fantastic. Then Coach will have  the ability not only to rebuild AlphaGo and also other far more complicated algo. We are very exciting to see that happens.

Best,

L. Lu

**Comment by itaicaspi-intel** [comment]
Thanks!
Can you clarify 1? any specific papers you had in mind?
Regarding 2 - it is not currently in our short term plans, but indeed, this can be a great extension that we will consider adding in the future.

**Comment by aGiant** [comment]
"Exploration can also be defined in the configuration object, which is applied by the agent to the action its model decided on (to handle multiple actions, again, a dictionary of specifications can be given). For instance, to use Ornstein-Uhlenbeck exploration for a continuous action output." and "epsilon exploration for a discrete action, which decays over time to a final value".

**Comment by itaicaspi-intel** [comment]
Sure, there are various exploration policies which are already supported.
Take a look [here](https://github.com/NervanaSystems/coach/tree/master/exploration_policies) for their definitions.
Choosing the exploration policy and its corresponding parameters can be done through the preset definition [here](https://github.com/NervanaSystems/coach/blob/master/presets.py)

**Comment by aGiant** [comment]
@itaicaspi-intel thanks for pointing it out

**Comment by galleibo-intel** [comment]
Hi @aGiant ,

Unfortunately, we do not plan to add support for MCTS any time soon. We will be very happy to get new contributions from the community.
