### ISSUE TITLE
Can I use LSTM networks with PPO?

### ISSUE THREAD

**Issue by bbalaji-ucsd** [NervanaSystems/coach#154]
The documentation doesn’t mention any explicit limitation and external papers have used LSTM before.

I get the following error when I try it with CartPole. Preset file: [CartPole_ClippedPPO_LSTM.txt](https://github.com/NervanaSystems/coach/files/2669987/CartPole_ClippedPPO_LSTM.txt)

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'main_level/agent/main/online/network_0/middleware_lstm_embedder/Placeholder_1' with dtype float and shape [1,256]
	 [[node main_level/agent/main/online/network_0/middleware_lstm_embedder/Placeholder_1 (defined at ../coach/rl_coach/architectures/tensorflow_components/middlewares/lstm_middleware.py:65)  = Placeholder[dtype=DT_FLOAT, shape=[1,256], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

**Comment by shadiendrawis** [comment]
I added support for clippedPPO with LSTM in PR number #156 with presets for CartPole and Mujoco.
You can check it out and see if the implementation suits your use case, as there are a few different ways you can approach implementing an LSTM middleware into ClippedPPO.

**Comment by galnov** [comment]
Closing this due to no response.
@bbalaji-ucsd please reopen with feedback on the PR if such support is needed.
