### ISSUE TITLE
Rollout and trainer total rewards are off by one

### ISSUE THREAD

**Issue by codyjhsieh** [NervanaSystems/coach#158]
<img width="950" alt="screen shot 2018-12-12 at 1 20 20 pm" src="https://user-images.githubusercontent.com/8563471/49899562-e6358880-fe10-11e8-99e0-ce959c31f05a.png">
Left is rollout and right is trainer

Trainer never shows 200 for CartPole_ClippedPPO 

**Reproduce:**
In separate terminals run
`python3 rl_coach/coach.py  -p CartPole_ClippedPPO --memory_backend_params '{"redis_address": "localhost", "redis_port": 6379, "store_type": "redispubsub", "channel": "channel-123"}' -dc  --distributed_coach_run_type trainer -e sample --checkpoint_save_secs 20 -asc`

and 

`python3 rl_coach/coach.py  -p CartPole_ClippedPPO --memory_backend_params '{"redis_address": "localhost", "redis_port": 6379, "store_type": "redispubsub", "channel": "channel-123"}' -dc  --distributed_coach_run_type rollout-worker -e sample --checkpoint_save_secs 20 -asc`

**Comment by scttl** [comment]
resolved via #168
