### ISSUE TITLE
Algorithms' Input/Details

### ISSUE THREAD

**Issue by mahsayedsalem** [NervanaSystems/coach#164]
I would like to know what input does, for example, Atari_A3C_Pong take?

Is it a stack of frames (How many frames by default, How to change) ? 
or just one frame?

**Comment by zach-nervana** [comment]
The default is stacking 4 frames: https://github.com/NervanaSystems/coach/blob/master/rl_coach/environments/gym_environment.py#L113

You can remove this filter with `input_filter.remove_observation_filter('observation', 'stacking')`. A different frame stacking filter can then be added.
