### ISSUE TITLE
windows play

### ISSUE THREAD

**Issue by babyldm** [NervanaSystems/coach#17]
windows cmd run:python coach.py -r -p CartPole_PG
get error
[93mWarning: failed to import the following packages - RoboSchool, Neon, ViZDoom, PyBullet, GymExtensions[0m
[30;46mPlease enter an experiment name: [0m
if i just wann play gym 'Pendulum-v0' not RoboSchool, Neon, ViZDoom, PyBullet,What should I do? 
installed ：
Intel® Distribution for Python （python3.6） 
tensorflow  1.3
annoy         1.9.1
Pillow          4.3.0

**Comment by itaicaspi-intel** [comment]
We did not test Coach on Windows, but it seems you were able to get it running.
The warning you are seeing is just a warning and not an error so you can ignore it in your case.
So just enter an experiment name (or leave it blank) and press enter to train.
To run Pendulum, use a predefined preset such as `-p Pendulum_NAF` or define your own preset (you can use one of the presets in presets.py as a reference)

**Comment by galleibo-intel** [comment]
Hi @babyldm,

Were you able to try Itai's suggestion?

**Comment by babyldm** [comment]
@galleibo-intel @itaicaspi-intel 
thanks,yes i have try , i am not a programmer，Just curiosity and test it， i use windows10 it have  Ubuntu，Thank for your reply，You are so professional and enthusiastic.

**Comment by galleibo-intel** [comment]
Thanks a lot. Closing the issue.
