### ISSUE TITLE
sample from space fails is_point_in_space_shape

### ISSUE THREAD

**Issue by davidkraljic** [NervanaSystems/coach#180]
Hi,
sampling from a space via sample() function in class Space fails the is_point_in_space_shape check. This seems like unexpected behavior. 

Potential issues: 
1. sampling from unbounded space checks whether either any low OR high bounds are infinite and then returns samples from standard normal distribution from (-np.inf, np.inf). What happens for semi-infinite spaces like e.g. [5, np.inf)?

2. is_point_in_space_shape() function is unclear. It seems like it's checking if the point _values_ are smaller than zero or that the point _values_ are bigger than shape (??). What about spaces with negative values?

I'd appreciate if you help me understand these issues.

**Comment by zach-nervana** [comment]
I believe the method you're looking for is `val_matches_space_definition`. `is_point_in_space_shape` appears to be checking if an multidimensional index into the observation space is valid.

I will update the docstrings and rename the methods to be more clear (while leaving the existing names for backwards compatibility).

`val_matches_space_definition -> contains`
`is_dot_in_space_shapen -> valid_index`
