### ISSUE TITLE
update trace values

### ISSUE THREAD

**Issue by scttl** [NervanaSystems/coach#189]
The expected trace values in `rl_coach/traces` haven't been updated/verified since prior to the last release and all trace tests are currently failing.

**Comment by galleibo-intel** [comment]
Does CircleCI has a functionality allowing to expose for the user to choose whether to commit the CI's latest generated traces (once the traces tests have completed and failed)? 

This could really ease the workflow with committing new traces to a PR after a change, which the author knows for a fact that should affect them. 

Also, in the past we have occasionally seen unfortunate cases where traces generated on different machines, running on exactly the same codebase, still resulted in diffs in the traces. We have not been able to nail down the exact cause for the issue, but it would really be helpful to just always push traces generated on the same machine/configuration.

**Comment by scttl** [comment]
Not exactly though it may be possible to hack something together depending on what you want.

Within a single job (say trace test execution) we could use Circle's conditional [on_fail](https://circleci.com/docs/2.0/configuration-reference/#the-when-attribute) status to execute something like a git push by the coachbot to the PR in question but this would happen on any previous step failure within that job and there would be no way to ask for the user to approve this first.

To have the user explicitly approve during a workflow we'd need to execute multiple jobs (one of which would be the approval), and I believe the only way to get to that job is to have all prior jobs pass (so wouldn't work if we're banking on trace tests failing to get to this job).

We may have more flexibility with the recently announced [github actions](https://github.com/features/actions/) but this is currently in beta and not yet available on our org account

**Comment by anabwan** [comment]
Done
