### ISSUE TITLE
Building CXX object error when installing with Neon support

### ISSUE THREAD

**Issue by dev1-fund3** [NervanaSystems/coach#19]
sudo ./install.sh works fine when not installing neon support
On AWS Ubuntu 16.02, python 2.7.12, 3.5.2:

Error when Install neon support option chosen:

> /home/ubuntu/coach/mkl-dnn/src/cpu/jit_avx512_common_conv_kernel.cpp: In lambda function:
/home/ubuntu/coach/mkl-dnn/src/cpu/jit_avx512_common_conv_kernel.cpp:2666:42: error: assuming signed overflow does not occur when assuming that (X + c) < X is always false [-Werror=strict-overflow]
     auto emit_fma_block = [&](int kh_step) {
                                          ^
cc1plus: all warnings being treated as errors
src/CMakeFiles/mkldnn.dir/build.make:782: recipe for target 'src/CMakeFiles/mkldnn.dir/cpu/jit_avx512_common_conv_kernel.cpp.o' failed
make[2]: *** [src/CMakeFiles/mkldnn.dir/cpu/jit_avx512_common_conv_kernel.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 40%] Linking CXX static library libmkldnn_gtest.a
[ 40%] Built target mkldnn_gtest
CMakeFiles/Makefile2:85: recipe for target 'src/CMakeFiles/mkldnn.dir/all' failed
make[1]: *** [src/CMakeFiles/mkldnn.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by itaicaspi-intel** [comment]
Seems like mkl-dnn installation is crashing.
mkl-dnn is not mandatory, but can boost performance a lot.
Please try following the instructions [here](https://software.intel.com/en-us/articles/intel-mkl-dnn-part-1-library-overview-and-installation) to install mkl-dnn manually.
I tested this instructions on a clean Ubuntu 16.04 with no issues.
Let me know if the manual installation also crashes.

**Comment by itaicaspi-intel** [comment]
This issue should be fixed following release 0.9.0.
I am closing the issue, please reopen it if the problem persists.
