### ISSUE TITLE
Support for Windows & MacOS

### ISSUE THREAD

**Issue by redknightlois** [NervanaSystems/coach#190]
Intel hardware runs not only on Linux. Would be great to have proper official support from Intel for other common operating systems being run on production or development environments. The underlying components like Tensorflow does support officially both.

**Comment by galnov** [comment]
Coach v1.0.0 can be installed and executed on MacOS.
Other users have been able to [run it on Windows](https://github.com/NervanaSystems/coach/issues/235#issuecomment-469048745).
