### ISSUE TITLE
How  to initialize network  weights

### ISSUE THREAD

**Issue by HubFire** [NervanaSystems/coach#197]
I want  to  transfer  pre-trained  network  weights to DDPG  critic  and  actor  network ,how  can I  do this in coach?

**Comment by galnov** [comment]
@HubFire can you please add more details on what you are trying to achieve?
Are you trying to load weights trained with Coach?
Do you want to continue training or only evaluate?

**Comment by galnov** [comment]
Closing due to no response.

**Comment by mattiasmar** [comment]
I too am interested to know if there exists an option today to use Coach to continue to train an existing network.

**Comment by mattiasmar** [comment]
Ping @galnov

**Comment by galnov** [comment]
You can save Coach checkpoints with the -s flag, and load those checkpoints for evaluation or to continue training by using the -crd flag. Loading weights of a model trained not using Coach is possible only if that model is an exact copy of the one used in Coach.

**Comment by nitsanluke** [comment]
@galnov I'm using RL Coach as a library, how can I evaluate with a saved model in a checkpoint file?

I'm able to save a checkpoint file once I'm done with training now I want to load that file again and evaluate on a (slightly) different environment. But the agent is exactly the same.

**Comment by nitsanluke** [comment]
@galleibo-intel  can I use `GraphManager.restore_checkpoint` to load trained model (structure & weights) to make test predictions (evaluate). Thanks!

**Comment by galleibo-intel** [comment]
Hi @nitsanluke,

Yes, you can definitely do that. Also, @shadiendrawis is now working on a change to ease the flow of working with Coach as a library.
