### ISSUE TITLE
Any benchmarking?

### ISSUE THREAD

**Issue by LinxiFan** [NervanaSystems/coach#2]
Is there any performance (speed and training curves) benchmarking? There are a great number of open-source RL alternatives on Github, but very few of them actually match (or even get close to) Deepmind's published results, for example.

**Comment by itaicaspi-intel** [comment]
Yes, we are planning to release some training curves in the near future.

**Comment by itaicaspi-intel** [comment]
We added some benchmarks [here](https://github.com/NervanaSystems/coach/tree/master/benchmarks)
