### ISSUE TITLE
AWS wrapper

### ISSUE THREAD

**Issue by aravind0706** [NervanaSystems/coach#21]
It would be good if there's a wrapper to run parallel jobs on AWS similar to rllab (basically have the docker file pulled from docker hub for this and set up everything with the AWS key).

**Comment by galleibo-intel** [comment]
Starting from release 0.11.0,  Coach can now run on AWS with Sagemaker RL. There are many notebook examples on the [Sagemaker RL examples repo](https://github.com/awslabs/amazon-sagemaker-examples/tree/master/reinforcement_learning).
