### ISSUE TITLE
NEC agent recovery problem 

### ISSUE THREAD

**Issue by tshh** [NervanaSystems/coach#22]
coached Pong_NEC for 3 days and got positive total reword each episode and using '-s 3600'.
then try to recovery the agent using '-crd' option from the experiment folder,
 total reword each episode drop to around -21 ~ -19 .

So, DND dictionary need to be save and recovery also, other than tensors , right ?

**Comment by galleibo-intel** [comment]
Thanks. This is indeed a bug. 
Fixed with 3c330768f0fbc3c5b94ad89a15ccdeaf77c173d8.

Closing.
