### ISSUE TITLE
CARLA - import error

### ISSUE THREAD

**Issue by Tar12** [NervanaSystems/coach#223]
Followed step-by-step instructions (Ubuntu 16.04, export CARLA_ROOT path)

Other environments work (e.g., coach -r -p CartPole_PG)

but 
coach -r -p CARLA_CIL

   from carla.driving_benchmark.experiment_suites import CoRL2017
ImportError: No module named 'carla'

I also tried using the dev branch here instead of pip3, same error. 
Tried with 0.8.2 and 0.8.4 versions of CARLA
Any ideas? Thanks!

**Comment by scttl** [comment]
Hi,

After you download the CARLA release tarball you'll also need to install the carla python client and dependencies.  Assuming you've unpacked the tarball to current directory something like:
```
pip3 install -r PythonClient/requirements.txt
pip3 install PythonClient
```
before you try running the preset should get you past that error.

I'll create a small PR to update the docs to make this more clear.

**Comment by lijecaru** [comment]
Sorry, how can I export CARLA_ROOT path?

**Comment by scttl** [comment]
@lijecaru did you use the 0.8.4 release?  One way in which this error could arise is if you run this from a different directory, or the `PythonClient` directory doesn't exist.  What does the unpacked directory look like for you?  For reference, here's what it shows for me:
```
sleishma@computer:/home/sleishma/repo/coach/carla> ls -la
total 1691492
drwxr-sr-x  5 sleishma aipg_labs       4096 Mar 13 22:50 .
drwxr-sr-x 16 sleishma aipg_labs      12288 Mar 13 22:48 ..
drwxr-sr-x  4 sleishma aipg_labs       4096 Jun 18  2018 CarlaUE4
-rwxr-xr-x  1 sleishma aipg_labs        246 Jun 18  2018 CarlaUE4.sh
-rw-r--r--  1 sleishma aipg_labs      15453 Jun 18  2018 CHANGELOG
-rw-r--r--  1 sleishma aipg_labs        673 Jun 18  2018 Dockerfile
drwxr-sr-x  6 sleishma aipg_labs       4096 Jun 18  2018 Engine
-rw-r--r--  1 sleishma aipg_labs       4154 Jun 18  2018 Example.CarlaSettings.ini
-rw-r--r--  1 sleishma aipg_labs       1133 Jun 18  2018 LICENSE
drwxr-sr-x  4 sleishma aipg_labs       4096 Jun 18  2018 PythonClient
-rw-r--r--  1 sleishma aipg_labs        211 Jun 18  2018 README
```

**Comment by Jidenna** [comment]
Here is my solution for those having error installing PythonClient. 

Instead of using pip3 install PythonClient
use pip3 install PythonClient/.

This will install the dependence found on the PythonClient/setup.py
