### ISSUE TITLE
Does coach work with TextWorld?

### ISSUE THREAD

**Issue by hsm207** [NervanaSystems/coach#229]
[TextWorld ](https://github.com/Microsoft/TextWorld#playing-a-game-python--gym) has an interface to Open AI's gym framework.

Does this mean it's possible to train an agent in TextWorld using the algorithms in coach?

**Comment by galnov** [comment]
You can use one of the LSTM based presets as a reference for training an agent with sequential input, but may need to adjust some of the network components (embedder/middleware) to successfully train a text based agent for TextWorld. If you are able to create a preset that does that, we'd be happy to get it as a PR.
