### ISSUE TITLE
C51 breakout default preset seems bad.

### ISSUE THREAD

**Issue by cxxgtxy** [NervanaSystems/coach#24]
Hi All,
I test C51 breakout. Finally, it can only get reward 1.0 which is bad enough. I wonder whether its hyper parameter has been fine tuned?

**Comment by itaicaspi-intel** [comment]
For how long did you run the training?
I also happen to have a partial run (only 1.5 million frames) from yesterday where it achieved higher scores than you are reporting  (around 40 after 1.5 million frames). 
This preset was verified to achieve similar results to the paper before, and should get to rewards of around 400-600 after 10 million frames.

**Comment by cxxgtxy** [comment]
Do you  use one worker or more?

**Comment by itaicaspi-intel** [comment]
after a second check I found out I had uncommitted fixes to this preset.
I fixed the presets in the following commit 8d9ee4e.
Thanks for pointing this out! Please let me know if it's working better now.

**Comment by cxxgtxy** [comment]
self.exploration.initial_epsilon = 1.0 I think this matters!

**Comment by itaicaspi-intel** [comment]
Yes I agree, that was probably the problem. Thanks again 👍

**Comment by cxxgtxy** [comment]
Welcome!
