### ISSUE TITLE
Read/write replay buffer from filesystem

### ISSUE THREAD

**Issue by mattiasmar** [NervanaSystems/coach#256]
Is there an option in Coach to read/write a replay buffer from/to filesystem?

**Comment by galnov** [comment]
Reading a replay buffer from file:
https://github.com/NervanaSystems/coach/blob/5d4b9c73998afe4928e49ee71f3a78aa81ca9a6f/rl_coach/memories/episodic/episodic_experience_replay.py#L406

**Comment by galnov** [comment]
Closing this issue for now. 
If there is a need for additional support on top of the above, feel free to reopen and add more details on the requested functionality.
