### ISSUE TITLE
The support for deepmind lab

### ISSUE THREAD

**Issue by ddayzzz** [NervanaSystems/coach#267]
[Deepmind lab](https://github.com/deepmind/lab) is a simulation enviroment like 3D maze whose observation is RGBD. And I want to know:
- Is any official support for developing interfaces(enviroment, observation)?
- How to extens observation class for depth and RGB observation? I noticed that RGBD format observation is marked as todo.

**Comment by galnov** [comment]
We are not planning to add support for DeepMind Lab, but are definitely open to such contributions from the community. Regarding RGBD support - the [PlanarMaps observation space](https://nervanasystems.github.io/coach/components/spaces.html#planarmapsobservationspace) defines a stack of 2D observations which can be used to represent RGBD images.

**Comment by ddayzzz** [comment]
Thank you for your advise. I managed to use the gym wrapper for the deepmind lab environment.
