### ISSUE TITLE
Gym latest version does not support dict_space

### ISSUE THREAD

**Issue by bbalaji-ucsd** [NervanaSystems/coach#269]
https://github.com/openai/gym/blob/master/gym/spaces/__init__.py#L7

'dict_space' has been renamed to 'dict'

Breaks coach here: 
https://github.com/NervanaSystems/coach/blob/master/rl_coach/environments/gym_environment.py#L324

**Comment by galleibo-intel** [comment]
Fixed with PR #254, which was just merged.
