### ISSUE TITLE
xrange vs range in agents/n_step_q_agent.py

### ISSUE THREAD

**Issue by ssamot** [NervanaSystems/coach#27]
Hello -  it seems that [agents/n_step_q_agent.py](agents/n_step_q_agent.py) uses xrange instead of range  - I guess this is a bug?

**Comment by itaicaspi-intel** [comment]
You are right, this is a bug. We will push a fix. Thanks!

**Comment by itaicaspi-intel** [comment]
should be fixed in the latest release 125c7ee
