### ISSUE TITLE
Mujoco tests are not running in CI

### ISSUE THREAD

**Issue by galleibo-intel** [NervanaSystems/coach#272]
`golden_test_mujoco` does not actually run mujoco’s golden tests. It seems that only BitFlip presets are run as part of the test. e.g. https://circleci.com/gh/NervanaSystems/coach/2057?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link 

This is although the circleci’s config.yaml is filtering for either BitFlip or Mujoco https://github.com/NervanaSystems/coach/blob/master/.circleci/config.yml#L241

**Comment by anabwan** [comment]
I can run both, bitflip and mujoco..
but since the name of the marker is "golden_test_mujoco", I think we should keep the mujoco test only,
I thinking of adding new golden for Bitflip, what you think ?

**Comment by galleibo-intel** [comment]
I don't think that BitFlip requires a category of its own. We can move it to the gym test category if you think it is helpful.

**Comment by anabwan** [comment]
fixed
https://github.com/NervanaSystems/coach/pull/274

**Comment by anabwan** [comment]
I see the bug... 
this is what I got:
Ayoob: {'args': ['export GOLDEN_PRESETS=CartPole or BitFlip && make '
          'golden_tests_without_docker'],

**Comment by anabwan** [comment]
fixed https://github.com/NervanaSystems/coach/pull/284
please review
