### ISSUE TITLE
The same argsort is performed batch_size times

### ISSUE THREAD

**Issue by Shmuma** [NervanaSystems/coach#28]
In this line we have np.argsort applied to all quantilles in the loop:
https://github.com/NervanaSystems/coach/blob/7bdba396d20bd54726a296af22b4e688af7f00cb/agents/qr_dqn_agent.py#L55

It would be batch_size times faster to calc it once.

**Comment by itaicaspi-intel** [comment]
Thanks! This improvement was added in 11faf19
