### ISSUE TITLE
Why abs_error is used?

### ISSUE THREAD

**Issue by Shmuma** [NervanaSystems/coach#29]
In the paper \sigma_{u < 0} is used, but you're using abs(u), which will always be non-negative.

https://github.com/NervanaSystems/coach/blob/7bdba396d20bd54726a296af22b4e688af7f00cb/architectures/tensorflow_components/heads.py#L530

**Comment by itaicaspi-intel** [comment]
Thanks for catching this. It is indeed a bug and was addressed in commit 11faf19
