### ISSUE TITLE
Typo on line 323 in gym_environment.py

### ISSUE THREAD

**Issue by molomono** [NervanaSystems/coach#305]
Since the new update to 0.12.0 a typo was introduced causing all OpenAI Gym environments to crash upon initialization.

Typo on line 323 in gym_environment.py:
`if not isinstance(self.env.observation_space, gym.spaces.dict.Dict):`

Should be:
`if not isinstance(self.env.observation_space, gym.spaces.Dict):`

This fixes the issue, on line 425 in the same document same line appears, but that line is actually already correct. 

My setup:
Operating system: Ubuntu 18.04 WSL on Windows 10
Use Case: When using any gym environment

**Comment by galnov** [comment]
Please upgrade to the latest gym version - 0.12.1.
