### ISSUE TITLE
Printing Agent Networks

### ISSUE THREAD

**Issue by nitsanluke** [NervanaSystems/coach#307]
`print_networks_summary` option from the visualization params only provides the input dense layer size. I would like to know whether can get the actual input shape of the environment observation ?
 I'm working on my own environment and I want to verify whether my environment is correctly set up to get the correct observation shape.

**Comment by galnov** [comment]
PR #310 adds input size to the printed network summary.

**Comment by nitsanluke** [comment]
@galnov  Sorry to re-open this again. I found that the prints give the same output for both LSTM and FC middleware layers. Is it something that is done purposefully. 

eg:
```
Input Embedder: observation
	Input size = [84, 84, 4]
	Input Normalization (scale = 255.0, offset = 0.0)
	Convolution (num filters = 32, kernel size = 8, stride = 4)
	Activation (type = <function relu at 0x1318082f0>)
	Convolution (num filters = 64, kernel size = 4, stride = 2)
	Activation (type = <function relu at 0x1318082f0>)
	Convolution (num filters = 64, kernel size = 3, stride = 1)
	Activation (type = <function relu at 0x1318082f0>)
Middleware:
	Dense (num outputs = 512)
	Activation (type = <function relu at 0x1318082f0>)
Output Head: v_values_head
	Dense (num outputs = 1)
Output Head: policy_values_head
	Dense (num outputs = 6)
	Softmax
```
`coach -r -p Atari_A3C_LSTM --print_networks_summary -lvl air_raid`
