### ISSUE TITLE
Error running with presets

### ISSUE THREAD

**Issue by JackieTseng** [NervanaSystems/coach#31]
Hey, I try to run DDPG without Presets with this command
```
 python coach.py -at DDPG -ept AdditiveNoiseExploration -et CartPole-v0
```
and get these errors,
```
Traceback (most recent call last):
  File "coach.py", line 255, in <module>
    tuning_parameters = json_to_preset(json_run_dict_path)
  File "/home/jackie/code/coach/presets.py", line 27, in json_to_preset
    tuning_parameters = Preset(eval(run_dict['agent_type']), eval(run_dict['environment_type']),
  File "<string>", line 1, in <module>
NameError: name 'CartPole' is not defined
```
I know what eval() means. However I can't find ways to fix this issue.
Any ideas? Or just providind an example without Presets will be nice. THX.

**Comment by itaicaspi-intel** [comment]
Hi Jackie,

The correct command line would be:
`python coach.py -at DDPG -ept AdditiveNoiseExploration -et GymVectorObservation -cp "env.level='CartPole-v0'"`

The flags `-at`, `-ept` and `-et` correspond to Preset class initializer parameters.
The flag `-cp` allows defining additional custom parameters.

With this said, keep in mind that DDPG is an algorithm which only supports continuous controls. CartPole on the other hand is a discrete controls environment where the actions are either 0 or 1.

**Comment by JackieTseng** [comment]
@itaicaspi-intel Thanks a lot.
