### ISSUE TITLE
DDPG  CARLA car  doesn't move  when training

### ISSUE THREAD

**Issue by HubFire** [NervanaSystems/coach#312]
Hi ,When I  run  CARLA DDPG  ,after 10 episodes ,the car doesn't  move . is there a trained model to test .

**Comment by galleibo-intel** [comment]
10 episodes is probably too little. Try to train some more. There were other issues of users successfully training an agent on Carla with DDPG.

**Comment by galnov** [comment]
Closing issue due to no response.
Please reopen if still not resolved.
