### ISSUE TITLE
Defining observation space dimensions

### ISSUE THREAD

**Issue by mattiasmar** [NervanaSystems/coach#318]
An openai gym.env defines  self.observation_space to 
```
 self.observation_space = spaces.Box(0, np.iinfo(np.int32).max,
                                            shape=(34,),
                                            dtype=float)
```

yet when using coach the below error is generated:
`ValueError: Cannot feed value of shape (1, 34) for Tensor 'main_level/agent/main/online/network_0/observation/observation:0', which has shape '(?, 0)'
`

The state returned by the said gym.env is a numpy float array of length 34.

**Comment by yunzhe-tao** [comment]
Hi, I met the same issue. How did you solve this? Thanks

**Comment by mattiasmar** [comment]
This is how I defined it:
```
self.observation_space = spaces.Box(0, np.iinfo(np.int32).max,
                                            shape=(self.observation_space_dim,),
                                            dtype=float)
```

This code belongs to the __init__ method of your environment.

**Comment by yunzhe-tao** [comment]
You just replaced 34 with self.observation_space_dim, right? Then why does it solve the issue?

**Comment by mattiasmar** [comment]
Unfortunately I don't remember what went wrong for me at the time. I have a weak memory that my observation_space_dim variable was not properly initialized. The error was not related to Coach per se and therefore I closed the issue myself.
