### ISSUE TITLE
imresize is deprecated, imresize is deprecated in SciPy

### ISSUE THREAD

**Issue by anabwan** [NervanaSystems/coach#320]
'imresize()' is deprecated! imresize is deprecated in SciPy 1.0.0, and it was removed in new version (1.2.0)

need to change: 
 - replacing imresize with skimage.transform.resize
 - verifying training results

current error:
  File "/root/src/rl_coach/filters/observation/observation_rescale_to_size_filter.py", line 83, in filter

    observation = scipy.misc.imresize(observation,

AttributeError: module 'scipy' has no attribute 'misc'

**Comment by galleibo-intel** [comment]
PR #321 fixes this issue.

**Comment by galleibo-intel** [comment]
Fixed with #321
