### ISSUE TITLE
Weight update during Evaluate (Testing)

### ISSUE THREAD

**Issue by nitsanluke** [NervanaSystems/coach#323]
Is there a way to switch between doing updates during the evaluation phase (testing).
- Currently in the `GraphManager. evaluate( ... )` weights are freezed?

**Comment by galleibo-intel** [comment]
Hi @nitsanluke, the evaluation phase (as the name suggests) is used for evaluating the last learned policy, resulting from the last training period. If wanted, you can either decrease the number of episodes or environment steps that are being executed at each evaluation phase in the `ScheduleParameters` defined in the preset.

**Comment by nitsanluke** [comment]
@galleibo-intel Thanks for the information. So in the evaluation phase, there aren't any online updates to the model is what you are confirming. Because online learning models generally are updating in the test as well. Thanks!
