### ISSUE TITLE
Can't visualize tensorflow graph

### ISSUE THREAD

**Issue by lrthorita** [NervanaSystems/coach#328]
I have run the CartPole_DQN preset to see how it works. After training, I tried to see the dashboard and the tensorboard.
The problem is that I can't see the Neural Network graph on tensorboard. Since the code saves the ''graphdef.pb", shouldn't it be there?

Basically, what I did was running the preset by using:
`coach -p CartPole_DQN -s 1800`
(I set `-s 1800` to save checkpoints of the model for each 30 minutes.

Then, I used `tensorboard --logdir /path/to/checkpoints/dir/` to try to see the neural network graph.

**Comment by galleibo-intel** [comment]
Hi @lrthorita, I am not sure why isn't the graph visible on Tensorboard on your setup. It is working fine over here, please see below. 

![image](https://user-images.githubusercontent.com/30383862/58403748-1940a100-806c-11e9-8684-ef39bea963f2.png)

Anyway, I don't think it is easy to understand the network layout from Tensorboard. This is why we have implemented a feature to textually summarize the graph layout, accessible through the `--print_networks_summary` flag. For instance, this is what you'll be getting for CartPole_DQN: 

Network: main, Copies: 2 (online network | target network)
----------------------------------------------------------
Input Embedder: observation
	Input size = [4]
	Dense (num outputs = 256)
	Activation (type = <function relu at 0x7f5958bcb378>)
Middleware:
	Dense (num outputs = 512)
	Activation (type = <function relu at 0x7f5958bcb378>)
Output Head: q_values_head
	Dense (num outputs = 2)

**Comment by lrthorita** [comment]
Hi @galleibo-intel! Thank you for answering.

I'll try the textual summary feature as soon as I can.
About the TensorFlow, is there any restriction about its version? I'm using 1.10.

**Comment by galleibo-intel** [comment]
Hi @lrthorita,

You're welcome. 
Yeah, 1.10 should be ok AFAIK.
