### ISSUE TITLE
Visualization problem

### ISSUE THREAD

**Issue by DihBastos** [NervanaSystems/coach#351]
Hey guys,

I'm new here and I trying to run the "0. Quick Start Guide.ipynb" with visualization

<pre>from rl_coach.agents.clipped_ppo_agent import ClippedPPOAgentParameters 
from rl_coach.environments.gym_environment import GymVectorEnvironment 
from rl_coach.graph_managers.basic_rl_graph_manager import BasicRLGraphManager
from rl_coach.graph_managers.graph_manager import SimpleSchedule 
from rl_coach.base_parameters import VisualizationParameters 
graph_manager = BasicRLGraphManager( 
    agent_params=ClippedPPOAgentParameters(), 
    env_params=GymVectorEnvironment(level='CartPole-v0'), 
    schedule_params=SimpleSchedule(), 
    vis_params= VisualizationParameters(render= True)
)
graph_manager.improve() </pre>

And I got this error:

<pre>File "/home/<user>/anaconda3/lib/python3.7/site-packages/gym-0.12.1-<br> py3.7.egg/gym/envs/classic_control/rendering.py", line 105, in render<br>
    arr = np.frombuffer(image_data.data, dtype=np.uint8)<br>
AttributeError: 'ImageData' object has no attribute 'data' </pre>

Anyone can help me?

**Comment by gal-leibovich** [comment]
This shouldn't happen. Chances are that this is some incompatibility with the Python packages installed on your system (you're using Anancoda with Python3.7). Could you please follow Coach's installation procedure [here](https://github.com/NervanaSystems/coach#installation), and report back if this issue still occurs?

**Comment by DihBastos** [comment]
> This shouldn't happen. Chances are that this is some incompatibility with the Python packages installed on your system (you're using Anancoda with Python3.7). Could you please follow Coach's installation procedure [here](https://github.com/NervanaSystems/coach#installation), and report back if this issue still occurs?

Thanks, man! I will try =)
