### ISSUE TITLE
Dashboard stuck

### ISSUE THREAD

**Issue by Seraphli** [NervanaSystems/coach#366]
I run this simple experiment `coach -p CartPole_DQN` first. Then the result is generated inside the `experiments` folder. I try to use the dashboard to visualize the result. 
The default requirements don't specify the version of `bokeh` and `tornado`. So I have `bokeh-1.2.0` and `tornado-6.0.3` installed. But when I try to open the `experiments` folder or the `csv` inside the folder. It stuck with the following error:
`RuntimeError: _pending_writes should be non-None when we have a document lock, and we should have the lock when the document changes`
Then I switch to `bokeh-1.0.4` and `tornado-5.1` according to #83. I can open the csv file, but the page stops responding when I refresh. The same error appears. When I select the folder, the message shows `Waiting for experiment directory to get populated...` and stays there forever.
I'm using Ubuntu 16.04 and coach from Github. Already install all dependency.

**Comment by dandanelbaz** [comment]
Dashboard stuck when upgrading bokeh version to latest (1.2.0), works with bokeh 1.0.4.

**Comment by philwinder** [comment]
For me it kind of works but is unbearably slow, which makes it impossible to use.

To be honest, I'd recommend removing the dashboard entirely.  IMO it's less than a "nice to have". It's simple to use some pandas to read and plot the CSV file. It's just bulk that ends up adding bugs.

**Comment by dandanelbaz** [comment]
We are having some issues migrating to the new version of Bokeh, not sure why.
running "pip install bokeh==1.0.4" should resolve the problem for now.
Thanks
