### ISSUE TITLE
Inconsistence of tutorial vs. documentation

### ISSUE THREAD

**Issue by luker963** [NervanaSystems/coach#408]
In [tutorial](https://github.com/NervanaSystems/coach/blob/9e82c06be3441ce1656c43f86e2045b9b351d678/tutorials/2.%20Adding%20an%20Environment.ipynb#L122) (line 122) is reference to `self.state` but documentation of [environment](https://github.com/NervanaSystems/coach/blob/9e82c06be3441ce1656c43f86e2045b9b351d678/rl_coach/environments/environment.py#L462) (line 462) is mentioned `self.observation`.
According to other environment examples, it seems that documentation of [environment](https://github.com/NervanaSystems/coach/blob/9e82c06be3441ce1656c43f86e2045b9b351d678/rl_coach/environments/environment.py#L462) is outdated.

**Comment by dandanelbaz** [comment]
The documentation of the environment will be updated in the next commit.
Thanks!
