### ISSUE TITLE
DDPG+HER: Multi-threaded or Multi-Node the way to go?

### ISSUE THREAD

**Issue by TobiKanone** [NervanaSystems/coach#409]
Hello everyone,

thank you for providing this awesome framework!
We are new to Coach and we are trying to train DDPG+HER on our own environment but we are unsure which is the way to go for us.
Which way to train the agent do you recommend for this algorithm? Multi-threaded or Multi-Node?
Any opinion is appreciated!
Thank you!

**Comment by galnov** [comment]
Hi, you can try single or multi-threaded which have been tested on various Fetch tasks as you can see [here](https://github.com/NervanaSystems/coach/tree/master/benchmarks/ddpg_her).
