### ISSUE TITLE
Bug: Install fails due to installing tensorflow 2.0

### ISSUE THREAD

**Issue by philwinder** [NervanaSystems/coach#415]
The [setup.py](https://github.com/NervanaSystems/coach/blob/master/setup.py) file has a pip restriction on tensorflow to `tensorflow>=1.9.0`. So tensorflow `2.0` is installed but coach is not compatible.

## Workaround

GPUs: `pip install tensorflow-gpu==1.14.0`
CPUs: `pip install intel-tensorflow==1.13.1`

**Comment by shadiendrawis** [comment]
Hi @philwinder,

Indeed, Coach doesn't currently support Tensorflow 2.0, I pushed a small patch to freeze the tensorflow version as a workaround.
We'll change that as soon as Coach becomes properly compatible with Tensorflow 2.0.

Shadi
