### ISSUE TITLE
Using billiard instead of multiprocessing package on rl_coach

### ISSUE THREAD

**Issue by gpanouts** [NervanaSystems/coach#429]
Hello,
I'm using rl_coach in combination with [Celery ](https://github.com/celery/celery)(a distributed task queue) in order to be able to spawn long-running RL tasks from within the flask framework. However, there is a compatibility issue. Celery does not support python package multiprocessing, but instead uses [billiard](https://github.com/celery/billiard) (which is forked from Python 2.7 multiprocessing package).

I've changed the parts of rl_coach code which use multiprocessing with billiard, and with a few experiments it seems that things work as expected. But is there a way to test this change more extensively? 

Thanks in advance.

I'm using:

rl-coach==1.0.1
billiard==3.6.1.0
gym==0.12.5

**Comment by galnov** [comment]
The full suite of Coach tests can be found [here](https://github.com/NervanaSystems/coach/tree/master/rl_coach/tests) - they should all be passing. If you would like to focus on multi-workers testing, it would be good to make sure convergence after your changes is similar to the graphs under the benchmarks folder, as in the A3C example [here](https://github.com/NervanaSystems/coach/tree/master/benchmarks/a3c).

**Comment by gpanouts** [comment]
@galnov Thanks for the feedback!
