### ISSUE TITLE
Coach on Raspberry Pi 4

### ISSUE THREAD

**Issue by Boubside** [NervanaSystems/coach#450]
I successfully manage to train an obstacle avoidance with distributed reinforcement learning using coach on AWS Robomaker/Sagemaker. Now I want to retrieve my model to use it for inference on the real robot. The brain of the robot Is a raspberry Pi 4.

So I tried to deploy on the Pi but the issue is I didn't manage to install rl_coach on the raspberry pi as there is no install wheel for intel_tensorflow on Raspbian. So my question is : is there a known way to install coach on a raspberry for inference ? 

Alternatively, can I save my file to a Tensorflow file format to use it for inference ? I already found the way to save the graph as a .pb file, but then i can't load it back as I don't know the names of input and output tensors (bascally, my issue for this is the same than #374 and #71, any improvement on these ones ?). Do you have any guidance on the best way to do it with a clipped PPO algorithm and a custom environment?

Thanks a lot.

**Comment by Lacan82** [comment]
I saw this and thought I'd throw out this comment. Would rl-coach-slim work for you? this was a packaged designed for robomaker/sagemaker. I believe it removes the tensorflow requirements.

when I run help on this package.

NAME
    rl_coach

PACKAGE CONTENTS
    agents (package)
    architectures (package)
    base_parameters
    checkpoint
    coach
    core_types
    dashboard
    dashboard_components (package)
    data_stores (package)
    debug_utils
    environments (package)
    exploration_policies (package)
    filters (package)
    graph_managers (package)
    level_manager
    logger
    memories (package)
    off_policy_evaluators (package)
    orchestrators (package)
    plot_atari
    presets (package)
    renderer
    rollout_worker
    run_multiple_seeds
    saver
    schedules
    spaces
    tests (package)
    training_worker
    utilities (package)
    utils

**Comment by Boubside** [comment]
Hi @Lacan82,
Thanks for your answer. I might try this in the future. Something that worked for me was to pull the source code of coach from the Git, bypassing the need for installation. I then use coach with a dummy environment (that only purpose is to define action and state spaces) to perform the inference. It work fine and i didn't add dependency issue, even if I don"t have Intel_tensorflow installed.
