### ISSUE TITLE
coach is missing top-level package for import-ability

### ISSUE THREAD

**Issue by zach-nervana** [NervanaSystems/coach#46]
coach is not organized with a top-level coach directory and is not pip installable, which makes it not importable unless the top-level script is in the coach directory.

Another issue with the current organization/install is that it makes running standard unit tests difficult since the unit tests can't import the coach modules. For now I have resorted to the following hack at the top of every unit test file:

```
import os
import sys
sys.path.append(os.path.dirname(os.path.dirname(os.path.dirname(__file__))))
```

**Comment by itaicaspi-intel** [comment]
Yeah I agree. We should restructure the directories as a python package (and make it pip installable at some point)

**Comment by zach-nervana** [comment]
after talking to Itai, it sounds like making coach pip installable is actually what's needed here, not just the top level directory.

**Comment by galleibo-intel** [comment]
Coach is now pip installable. See README for more details. As for external importability as a library, here is an example for using Coach algorithms to solve a completely different environment - 

https://github.com/NervanaSystems/distiller/blob/master/examples/automated_deep_compression/ADC.py#L103
