### ISSUE TITLE
inputs should be specified as a dictionary instead of list

### ISSUE THREAD

**Issue by zach-nervana** [NervanaSystems/coach#48]
Right now, the input to the neural networks are represented as lists and only converted into a dictionary at the last minute. The order of this list needs to be kept synchronized in multiple places which makes understanding the code and debugging more difficult. It also makes it difficult to compose multiple concepts which expect special orders.

More specifically, `tuning_parameters.InputTypes` input order must match `Agent.inputs` and `Agent.extract_batch`.

This is also a helpful first step towards allowing the environment to supply multiple inputs. For example right now there can only be a single image input.

**Comment by itaicaspi-intel** [comment]
I agree. The current method is confusing

**Comment by galleibo-intel** [comment]
this is fixed with release 0.10.
