### ISSUE TITLE
Testing Coach on Ubuntu 17.10 and Python 3.6.3 

### ISSUE THREAD

**Issue by pedronahum** [NervanaSystems/coach#54]
Hi,

I am currently testing Coach on Ubuntu 17.10 and Python 3.6.3. 

With a few changes in the install.sh file, Coach seems to be fully functional.  

# Dashboard requirements: 
* replace python3.5-dev to python3.6-dev
* Inside coach_env: pip install wxpython (instead of apt-get)

# NGraph (install protobuf compiler before installing NGraph):
sudo apt install protobuf-compiler

# Intel Optimized TensorFlow (replace CPU link)
pip install https://anaconda.org/intel/tensorflow/1.4.0/download/tensorflow-1.4.0-cp36-cp36m-linux_x86_64.whl

I havent tested CARLA yet, but so far so good. 

Needless to say, great work with Coach!

**Comment by itaicaspi-intel** [comment]
Hi Pedro,
Thanks for letting us know, your help is very much appreciated!
We will add these changes to the installation script and README file so that others would be able to use it as well.
Keep up the good work!

**Comment by pedronahum** [comment]
Hi, 

Happy to help! Just let me know if you need me to test the updated script. 

Best

**Comment by pedronahum** [comment]
Hi Itai,

FYI, in a fresh Ubuntu 16.04.3 LTS install, the NGraph installation logic will fail if the protobuf-compiler is not installed. I think adding "sudo apt install protobuf-compiler" is a safe bet. 

In https://github.com/NervanaSystems/ngraph/blob/master/Makefile, line 306 the specify:
ifeq ("$(UNAME)", "Darwin")
	brew install protobuf
else ifeq ("$(UNAME)", "Linux")
	sudo apt-get install protobuf-compiler libprotobuf-dev
endif

Hope this helps!

**Comment by galleibo-intel** [comment]
Hi @pedronahum ,
NGraph/Neon are no longer supported. Thanks for the help with the instructions on using with Ubuntu 17.10 and Python3.6!
