### ISSUE TITLE
dump_output_csv rewrites log file on every update

### ISSUE THREAD

**Issue by zach-nervana** [NervanaSystems/coach#57]
It seems that the file generated by `dump_output_csv` is removed and rewritten every 10 episodes by default. Ideally the log file could be written to incrementally instead of from scratch so that the log file can both be up to date and also efficient.

On fast local storage, inefficient writes are not a big deal, however I am currently writing my logs to nfs where this inefficiency is definitely an issue.

**Comment by itaicaspi-intel** [comment]
Good point. And also should be easy to fix

**Comment by itaicaspi-intel** [comment]
Addressed in commit ba96e585d2ac8e1f940080d5b669976bdec8723b
