### ISSUE TITLE
Install Script Error When Headless and Installing Neon

### ISSUE THREAD

**Issue by zac-hopkinson** [NervanaSystems/coach#6]
When running the `install.sh` script in an automated/headless manner, I get this error:

```plain
./install.sh: line 171: [: -eq: unary operator expected
````

Ran with:

```bash
./install.sh -c -p -g -N -ne -d
```

Running the headless installation way, `$INSTALL_NEON` never gets set.

Comparing as if it was a string would have worked since an unset variable would just become "" on a string comparison w/ `==`. Since it's a numeric comparison w/ `-eq` it causes an error.

**Comment by galleibo-intel** [comment]
Fixed by PR #7
