### ISSUE TITLE
invalid object?

### ISSUE THREAD

**Issue by jtoy** [NervanaSystems/coach#68]
I just tested running coach from source: 4fe9cba44508f258fc73286d6cbf0af4b1fdfa50

on both ubuntu 14.04 and Macos high Sierra and I get the exact same error:

python coach.py -p CartPole_DQN -r
```
/home/jtoy/anaconda3/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
Warning: failed to import the following packages - RoboSchool, GymExtensions, ViZDoom, CARLA, Neon
Please enter an experiment name: test
Using tensorflow framework
Traceback (most recent call last):
  File "coach.py", line 275, in <module>
    env_instance = create_environment(tuning_parameters)
  File "/home/jtoy/sandbox/touchnet/related_projects/coach/environments/__init__.py", line 32, in create_environment
    env = eval(env_type)(tuning_parameters)
  File "/home/jtoy/anaconda3/lib/python3.6/site-packages/pandas/core/computation/eval.py", line 267, in eval
    ret = eng_inst.evaluate()
  File "/home/jtoy/anaconda3/lib/python3.6/site-packages/pandas/core/computation/engines.py", line 75, in evaluate
    res = self._evaluate()
  File "/home/jtoy/anaconda3/lib/python3.6/site-packages/pandas/core/computation/engines.py", line 122, in _evaluate
    return ne.evaluate(s, local_dict=scope, truediv=truediv)
  File "/home/jtoy/anaconda3/lib/python3.6/site-packages/numexpr/necompiler.py", line 807, in evaluate
    zip(names, arguments)]
  File "/home/jtoy/anaconda3/lib/python3.6/site-packages/numexpr/necompiler.py", line 806, in <listcomp>
    signature = [(name, getType(arg)) for (name, arg) in
  File "/home/jtoy/anaconda3/lib/python3.6/site-packages/numexpr/necompiler.py", line 704, in getType
    raise ValueError("unknown type %s" % a.dtype.name)
ValueError: unknown type object
```

I installed all dependencies with pip install -r  requirements_coach.txt 

Is there an issue in master or am I missing something basic?

**Comment by jtoy** [comment]
its because coach doesn't work on ubuntu 14.04 or mac,  only 16.04. Would it be helpful if I added a docker image?

**Comment by zach-nervana** [comment]
we internally have docker images, but cannot add them to this repository for licensing reasons that we are hopefully working out. Hopefully we can include one soon, thank you.

**Comment by jtoy** [comment]
I just wrote a Dockerfile  that works with CPU tensorflow, can I send a PR for this?

**Comment by zach-nervana** [comment]
Unfortunately I don't think we can merge it yet if you do, @galnov what is the status of including Dockerfiles in this repository?

**Comment by jtoy** [comment]
Here is my Dockerfile incase you all want it: https://gist.github.com/jtoy/2fee28d8931de0ce6b5883e4b5658560

**Comment by galleibo-intel** [comment]
Thanks @jtoy! 
As @zach-nervana mentioned, at the moment we cannot merge the Dockerfile in. 
Closing the issue.

**Comment by r-lipton** [comment]
I have the exact same problem running the example on a RHEL7.
Why it is only compatible with Ubuntu 16.04 ? The only solution is to use a docker container ?

**Comment by r-lipton** [comment]
Seems like it's the eval function from pandas that does not work. 
Using the python built-in eval did the job

**Comment by jtoy** [comment]
fixed it and now have coach working on Mac and ubuntu 14.04! I'll submit a PR.

**Comment by jtoy** [comment]
here is the fix: https://github.com/NervanaSystems/coach/pull/91
