### ISSUE TITLE
CARLA Render on Multiple GPUs?

### ISSUE THREAD

**Issue by bhairavmehta95** [NervanaSystems/coach#70]
Does the default coach system render CARLA on multiple GPUs? Or does it just set it to the default one? I couldn't get it running to check, so I figured this may be faster to get an answer.

**Comment by itaicaspi-intel** [comment]
Coach currently only supports 1 GPU for CARLA
Carla has a solution that uses vnc and virtualgl to implement it, but it is not implemented in Coach.
Have a look at [this thread](https://github.com/carla-simulator/carla/issues/116
) for more info

**Comment by bhairavmehta95** [comment]
Gotcha; I've been using the instructions from there to set up a multi-gpu setup, but was having some problems with communication so I thought I'd use the coach implementation if it was available. Thanks again!
