### ISSUE TITLE
Unity3D environment

### ISSUE THREAD

**Issue by r-lipton** [NervanaSystems/coach#73]
Hey
Do you plan to make a wrapper for Unity [ml-agents ](https://github.com/Unity-Technologies/ml-agents)?

**Comment by galleibo-intel** [comment]
Hi,

We have looked into it in the past, but currently, unfortunately, we have no such plans. We would be happy to merge in a PR for supporting ml-agents, together with a preset solving one of the pre-built scenarios. Documentation for adding a new environment into Coach can be found [here](http://coach.nervanasys.com/contributing/add_env/index.html).
