### ISSUE TITLE
How do you create the design image of the algorithms?

### ISSUE THREAD

**Issue by eyyi** [NervanaSystems/coach#78]
Hi,

how do you create the design image of the algorithms? 
I've implemented the _[FiGAR](https://arxiv.org/abs/1702.06054)_ algorithm. 

I would like to create an image of the algorithm.  

Thx,
Gabriel

**Comment by itaicaspi-intel** [comment]
Great to hear that you have found Coach useful.
We create the images manually using Visio and have an internal template.
We will try to release the template soon, so that you can use it for your algorithm.

**Comment by itaicaspi-intel** [comment]
We now have the design files as part of the repository [here](https://github.com/NervanaSystems/coach/blob/master/docs_raw/docs/diagrams.xml).
We moved to using www.draw.io so that it will be easier to edit and customize.
