### ISSUE TITLE
some wonderful algorithm

### ISSUE THREAD

**Issue by zdx3578** [NervanaSystems/coach#79]
https://github.com/pathak22/noreward-rl
https://pathak22.github.io/noreward-rl/
realAI for Deep Reinforcement Learning
ICM algorithm ? （Curiosity-driven Exploration for Deep Reinforcement Learning - realAI

**Comment by itaicaspi-intel** [comment]
It is currently not planned, but we are open for contributions

**Comment by zdx3578** [comment]
https://github.com/openai/baselines/tree/master/baselines/her

**Comment by zach-nervana** [comment]
We have an implementation of HER in a private branch, maybe will come with next release.

**Comment by zdx3578** [comment]
world models  https://worldmodels.github.io

**Comment by itaicaspi-intel** [comment]
Thanks for the references. We add new algorithms to Coach from time to time, but the field is growing too fast for us to add all of them. We are open for contributions and encourage you to add new implementations to Coach and submit them as PRs. I am closing this issue for now. Thanks again!

**Comment by zdx3578** [comment]
https://github.com/vitchyr/rlkit/blob/master/rlkit/torch/tdm/TDMs.md

**Comment by zdx3578** [comment]
https://github.com/createamind/Imagination-Augmented-Agents/blob/master/README.md

**Comment by zdx3578** [comment]
https://github.com/createamind/Imagination-Augmented-Agents/blob/master/README.md
