### ISSUE TITLE
Wrong Python Interpreter If Installed With --no_virtual_environment

### ISSUE THREAD

**Issue by zac-hopkinson** [NervanaSystems/coach#8]
If you install with `--no_virtual_environment` then the calls in `coach.py` to run `python` call the system's Python 2 instead of 3.

Tested inside of a fresh `ubuntu:16.04` Docker image. Installed with `./install.sh -c -p -g -N -ne -d`.

Might be as simple as changing `python` to `python3` in these two locations?

https://github.com/NervanaSystems/coach/blob/6009b73eb60f6a79daa2a0028f8feafda3635f7d/coach.py#L276

https://github.com/NervanaSystems/coach/blob/6009b73eb60f6a79daa2a0028f8feafda3635f7d/coach.py#L299

**Comment by galleibo-intel** [comment]
Thanks a lot for catching this Zac ! 
Fixed with 1a09b7cec3860042184841da6773ff3f96f1c0c9
