### ISSUE TITLE
dumping gifs not working?

### ISSUE THREAD

**Issue by jtoy** [NervanaSystems/coach#81]
Dumping gifs seems to not work, I tried running passing the -dg option with a couple of environments for over 30 mins with over 400 episodes and it never seems to output gifs
I ran these commands:
python3 coach.py -p CartPole_DQN -dg
python3 coach.py -p Breakout_A3C  -dg

here you can see output:
https://cl.ly/173A092l112H

```
find experiments/
experiments/
experiments/asdsad
experiments/asdsad/20_03_2018-14_29
experiments/asdsad/20_03_2018-14_29/run_dict_worker3.json
experiments/asdsad/20_03_2018-14_29/run_dict_worker0.json
experiments/asdsad/20_03_2018-14_29/run_dict_worker1.json
experiments/asdsad/20_03_2018-14_29/run_dict_worker4.json
experiments/asdsad/20_03_2018-14_29/run_dict_worker2.json
experiments/asdads
experiments/asdads/20_03_2018-14_30
experiments/asdads/20_03_2018-14_30/run_dict.json
experiments/asdads/20_03_2018-14_30/worker_20_03_2018-14_30_0.csv
experiments/sadd
experiments/sadd/20_03_2018-14_29
experiments/sadd/20_03_2018-14_29/worker_20_03_2018-14_29_0.csv
experiments/sadd/20_03_2018-14_29/run_dict.json
experiments/gifs
experiments/gifs/20_03_2018-14_36
experiments/gifs/20_03_2018-14_36/run_dict.json
experiments/gifs/20_03_2018-14_36/worker_20_03_2018-14_36_0.csv
experiments/efewf
experiments/efewf/20_03_2018-14_36
experiments/efewf/20_03_2018-14_36/run_dict.json
experiments/efewf/20_03_2018-14_36/worker_20_03_2018-14_36_0.csv
```

**Comment by KuenstlicheIntelligenz** [comment]
Did you changed the evaluation parameters?
If you didn't they may be set to way more then 400 episodes.

**Comment by sowmyabobba27** [comment]
I have similar issue, dump gif option is only working for preset "Breakout_A3C". I have tried it with other presets but, it doesn't seem to be producing any gifs. I tried to change configuration.py parameters but that didn't fix anything.

**Comment by sowmyabobba27** [comment]
@itaicaspi-intel should i add these evaluate_every_x_episodes and evaluation_episodes parameters for every preset I want the gifs to be produced in the following file ?
https://github.com/NervanaSystems/coach/blob/master/presets.py

**Comment by jtoy** [comment]
this is solved for me as well by using the suggested values, I would suggest explicitly talking about this in the docs and giving an example preset that will save gifs more frequently.
