### ISSUE TITLE
end training after reaching certain criteria

### ISSUE THREAD

**Issue by jtoy** [NervanaSystems/coach#82]
I've trained a dozen or so networks with coach now. To end training,I always hit control-c after running for a couple of days, not sure if it will ever end if I just leave it.  Is there a way to end early training early, such as after N number of episodes or after N number of hours. If not, is the useful to add?

**Comment by itaicaspi-intel** [comment]
Currently we support defining the length of the experiment in terms of training iterations. It is enforced through the improve function [here](https://github.com/NervanaSystems/coach/blob/cafa152382e057eb376b869bda011cc08c0fd7f9/agents/agent.py#L521). Defining it in terms of episodes / hours is a good idea. We will definitely add this option soon.

**Comment by itaicaspi-intel** [comment]
Sure, we completely understand the need for this option.
This will be configurable in a new version of Coach we are working on and are planning to release in the next months.

**Comment by itaicaspi-intel** [comment]
Hi @jtoy, 
the new version is now released and this is available through the scheduling parameters in the presets.
