### ISSUE TITLE
Problem when running dashboard

### ISSUE THREAD

**Issue by maxtomCMU** [NervanaSystems/coach#86]
When I try to run dashboard.py, there is always the error.
`(coach_env) maxtom@robot:~/coach$ python dashboard.py `
`ERROR:cannot import name 'locks'`

**Comment by itaicaspi-intel** [comment]
Seems like a bokeh / tornado compatibility issue.
Can you please make sure you have the following version installed:
```
tornado==4.5.1
bokeh==0.12.7
```

**Comment by itaicaspi-intel** [comment]
@maxtomCMU I am closing this issue for now. If the issue persists, please reopen the issue.
