### ISSUE TITLE
OpenAI Gym Latest Version Incompatible with Example

### ISSUE THREAD

**Issue by zac-hopkinson** [NervanaSystems/coach#9]
The latest OpenAI gym doesn't come with `BreakoutDeterministic-v3`.

They mention it here: https://github.com/openai/gym#whats-new

> 2017-05-13: BACKWARDS INCOMPATIBILITY: The Atari environments are now at v4. To keep using the old v3 environments, keep gym <= 0.8.2 and atari-py <= 0.0.21. Note that the v4 environments will not give identical results to existing v3 results, although differences are minor.

To downgrade you can run:

```bash
pip install gym[atari]==0.8.2
```

This gets the `Breakout_A3C` preset to work. I haven't tried replacing the preset with `BreakoutDeterministic-v4` yet.

Looks like Breakout wouldn't work without installing `gym[atari]` vs just `gym` anyway:

https://github.com/NervanaSystems/coach/blob/6009b73eb60f6a79daa2a0028f8feafda3635f7d/install.sh#L171

And it's for this preset:

https://github.com/NervanaSystems/coach/blob/e813eaf304d728a7655b5343ca1eb7cd2ba32e74/presets.py#L1123

**Comment by itaicaspi-intel** [comment]
Hi Zac, thanks for bringing this up!
We are working with the latest gym version so v4 should be used.
We pushed a fix for this issue in the following commit: 
https://github.com/NervanaSystems/coach/commit/43bc35916621589bbac101eee11c5640a521067d
