### ISSUE TITLE
Solution for Coach Connecting Carla

### ISSUE THREAD

**Issue by zjuybx** [NervanaSystems/coach#90]
There is a bug for Coach Connecting  Carla. It is beacause the some functions are not completed. It leads in the "self.observation" can not be transfered to the "state". Besides, the "_preprocess_observation" was not rewrite in the child class. To fix that, rewrite the "__preprocess_observation" as 

**def** _preprocess_observation(self, observation):
    if observation is None:
        return None
    if self.done:
        return observation
    return observation

Besides, it seems that "self.state" is the same object as "**self**.observation". In "_update_state" in carla_environment_wrapper.py, insert 
        **self**.state = **self**.observation

Moreover, the assignment of observation cannot work, we modify the @property and @property.setter with observation={}

By the way, Coach offer a free port for every reset of Carla environment, but Carla need three ports. All the three port should be free.

Anathor issue is that when you use the release of Carla, the enviroment cannot read the ini file. The enviroment is set by coding.

Appreciated for the work of Carla group@intel
   
From.   zjuybx & junweifu

**Comment by itaicaspi-intel** [comment]
Hi @zjuybx and @junweifu, thanks for letting us know.
There was indeed a bug that resulted from a refactoring of the code that was done earlier this year.
We now have a new version in which this is fixed and should be working correctly.
Please reopen the issue if it persists.
