### ISSUE TITLE
examples

### ISSUE THREAD

**Issue by jerabaul29** [NervanaSystems/coach#97]
Hi!

Thank you for this nice project.

I find it a bit difficult to get started (outside of the coach.py examples). For example, I cannot find how to define the network to be given to an agent.

Would it be possible to get an *examples* folder, with some simple self-contained examples of how to fully set up a learning algorithm on some simple game? For example, implementing an example script for showing how to train on the 2048 game? Maybe also a simple self-contained example with PPO for continuous action control.

**Comment by itaicaspi-intel** [comment]
Thanks @jerabaul29,
We agree that the ramp up time for coach is an issue and needs to be reduced.
We added a tutorials directory with some python notebooks to help ease this phase.
We will definitely add some more to explain the presets mechanism and how to define networks, setting up an experiment, etc. 
Stay tuned

**Comment by galleibo-intel** [comment]
We have improved documentation and added new tutorials, with release 0.11.0. I think that this resolves this issue. Please re-open if you still think that the ramp up materials are lacking.
